// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FashionEcommerce.Api.Data;

#nullable disable

namespace FashionEcommerce.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306231745_AddPriceToProductVariant")]
    partial class AddPriceToProductVariant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Simplified; in real scenario, this would be the full model
        }
    }
}